/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context } from "./../context"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    model: NexusPrisma<TypeName, 'model'>
    crud: any
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  MajorityType: "QUALIFIED" | "SIMPLE"
  Status: "ENDED" | "ONGOING" | "UPCOMING"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Alternative: { // root type
    id: string; // ID!
    text: string; // String!
    votation?: NexusGenRootTypes['Votation'] | null; // Votation
  }
  Meeting: { // root type
    description?: string | null; // String
    id: string; // ID!
    startTime: string; // String!
    status: NexusGenEnums['Status']; // Status!
    title: string; // String!
    votations?: Array<NexusGenRootTypes['Votation'] | null> | null; // [Votation]
  }
  Mutation: {};
  Query: {};
  User: { // root type
    email: string; // String!
    id: string; // ID!
    username: string; // String!
  }
  Votation: { // root type
    alternatives?: Array<NexusGenRootTypes['Alternative'] | null> | null; // [Alternative]
    blankVotes?: boolean | null; // Boolean
    description: string; // String!
    hasVoted?: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    id: string; // ID!
    majorityThreshold: number; // Int!
    majorityType: NexusGenEnums['MajorityType']; // MajorityType!
    meeting: NexusGenRootTypes['Meeting']; // Meeting!
    order?: number | null; // Int
    status: NexusGenEnums['Status']; // Status!
    title: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Alternative: { // field return type
    id: string; // ID!
    text: string; // String!
    votation: NexusGenRootTypes['Votation'] | null; // Votation
  }
  Meeting: { // field return type
    description: string | null; // String
    id: string; // ID!
    owner: NexusGenRootTypes['User']; // User!
    startTime: string; // String!
    status: NexusGenEnums['Status']; // Status!
    title: string; // String!
    votations: Array<NexusGenRootTypes['Votation'] | null> | null; // [Votation]
  }
  Mutation: { // field return type
    addUser: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    hello: Array<NexusGenRootTypes['Alternative'] | null> | null; // [Alternative]
    meetings: Array<NexusGenRootTypes['Meeting'] | null>; // [Meeting]!
    users: Array<NexusGenRootTypes['User'] | null>; // [User]!
  }
  User: { // field return type
    email: string; // String!
    id: string; // ID!
    username: string; // String!
  }
  Votation: { // field return type
    alternatives: Array<NexusGenRootTypes['Alternative'] | null> | null; // [Alternative]
    blankVotes: boolean | null; // Boolean
    description: string; // String!
    hasVoted: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    id: string; // ID!
    majorityThreshold: number; // Int!
    majorityType: NexusGenEnums['MajorityType']; // MajorityType!
    meeting: NexusGenRootTypes['Meeting']; // Meeting!
    order: number | null; // Int
    status: NexusGenEnums['Status']; // Status!
    title: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Alternative: { // field return type name
    id: 'ID'
    text: 'String'
    votation: 'Votation'
  }
  Meeting: { // field return type name
    description: 'String'
    id: 'ID'
    owner: 'User'
    startTime: 'String'
    status: 'Status'
    title: 'String'
    votations: 'Votation'
  }
  Mutation: { // field return type name
    addUser: 'User'
  }
  Query: { // field return type name
    hello: 'Alternative'
    meetings: 'Meeting'
    users: 'User'
  }
  User: { // field return type name
    email: 'String'
    id: 'ID'
    username: 'String'
  }
  Votation: { // field return type name
    alternatives: 'Alternative'
    blankVotes: 'Boolean'
    description: 'String'
    hasVoted: 'User'
    id: 'ID'
    majorityThreshold: 'Int'
    majorityType: 'MajorityType'
    meeting: 'Meeting'
    order: 'Int'
    status: 'Status'
    title: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addUser: { // args
      email: string; // String!
      id: string; // String!
      username: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}